name: Publish npm

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    if: github.event.release.draft == false
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        shell: bash
    env:
      GH_PACKAGES_USERNAME: ${{ secrets.GH_PACKAGES_USERNAME || 'matchingtool-cedeirasf' }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN || secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}

      # setup node
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'
        
      # setup pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Cache pnpm dependencies
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
     
      # Generate npm package
      - name: Generate npm package
        run: pnpm pack

      # Publish npm package into private github registry
      - name: Publish npm package
        run: pnpm publish --access public --registry https://npm.pkg.github.com
